import PDFDocument from "pdfkit";
import path from "path";

export type ScanIndicator = {
  name: string;
  nameAm?: string;
  detected: boolean;
  severity: "low" | "medium" | "high";
  description?: string;
};

export type ScanReport = {
  id: string;
  inputType: "url" | "sms" | "email";
  result: "safe" | "suspicious" | "phishing";
  confidence: number;
  riskScore?: number | null;
  riskLevel?: "low" | "medium" | "high" | null;
  contentPreview?: string | null;
  createdAt: Date;
  institution?: string | null;
  summary?: string | null;
  summaryAm?: string | null;
  indicators: ScanIndicator[];
};

const PROJECT_NAME = "PhishGuard Ethiopia";
const REPORT_TITLE = "Official Phishing Threat Analysis Report";
const ORGANIZATION = "PhishGuard Cyber Defense Initiative";
const CLASSIFICATION = "CONFIDENTIAL";
const FOOTER_LINE_1 = "Generated by PhishGuard Ethiopia — Confidential Security Report";
const FOOTER_LINE_2 = "For authorized use only";

const FONT_PATH = path.join(process.cwd(), "assets", "fonts", "NotoSansEthiopic.ttf");

const formatEAT = (date: Date) =>
  date.toLocaleString("en-US", { timeZone: "Africa/Addis_Ababa" }) + " (EAT)";

const riskLabel = (score: number) => (score >= 86 ? "CRITICAL" : score >= 61 ? "HIGH" : score >= 31 ? "MEDIUM" : "LOW");

const badgeColors = (level: string) => {
  if (level === "CRITICAL" || level === "HIGH") return { fill: "#FEE2E2", text: "#DC2626" };
  if (level === "MEDIUM") return { fill: "#FFEDD5", text: "#D97706" };
  return { fill: "#DCFCE7", text: "#16A34A" };
};

const verdictBadge = (verdict: string) => {
  if (verdict === "PHISHING") return { fill: "#FEE2E2", text: "#DC2626" };
  if (verdict === "SUSPICIOUS") return { fill: "#FFEDD5", text: "#D97706" };
  return { fill: "#DCFCE7", text: "#16A34A" };
};

const drawShieldIcon = (doc: PDFDocumentType, x: number, y: number) => {
  doc.save();
  doc.path(`M ${x + 12} ${y} L ${x + 26} ${y + 6} L ${x + 26} ${y + 20} L ${x + 12} ${y + 30} L ${x - 2} ${y + 20} L ${x - 2} ${y + 6} Z`)
    .fill("#0F172A");
  doc.path(`M ${x + 12} ${y + 4} L ${x + 22} ${y + 8} L ${x + 22} ${y + 18} L ${x + 12} ${y + 26} L ${x + 2} ${y + 18} L ${x + 2} ${y + 8} Z`)
    .fill("#38BDF8");
  doc.restore();
};

const drawCard = (doc: PDFDocumentType, x: number, y: number, w: number, h: number) => {
  doc.roundedRect(x, y, w, h, 6).fill("#F8FAFC");
  doc.roundedRect(x, y, w, h, 6).strokeColor("#E2E8F0").stroke();
};

const drawSectionHeader = (doc: PDFDocumentType, title: string, y: number) => {
  doc.fontSize(12).fillColor("#0F172A").text(title, 40, y);
  doc.moveTo(40, y + 16).lineTo(555, y + 16).strokeColor("#E2E8F0").stroke();
};

const iconCircle = (doc: PDFDocumentType, x: number, y: number, color: string) => {
  doc.circle(x, y, 4).fill(color);
};

const iconTriangle = (doc: PDFDocumentType, x: number, y: number, color: string) => {
  doc.path(`M ${x} ${y} L ${x + 8} ${y + 14} L ${x - 8} ${y + 14} Z`).fill(color);
};

type PDFDocumentType = InstanceType<typeof PDFDocument>;

const addFooter = (doc: PDFDocumentType) => {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    const pageHeight = doc.page.height;
    doc.fontSize(8).fillColor("#5F6B7A");
    doc.text(FOOTER_LINE_1, 40, pageHeight - 60, { align: "left" });
    doc.text(FOOTER_LINE_2, 40, pageHeight - 48, { align: "left" });
    doc.fontSize(9).fillColor("#1F2937");
    doc.text(`Page ${i + 1} of ${range.count}`, 40, pageHeight - 34, { align: "left" });
    doc.text("PhishGuard Ethiopia • Trusted Cyber Defense", 320, pageHeight - 34, { align: "right" });
  }
};

const sectionTitle = (doc: PDFDocumentType, title: string, y: number) => {
  doc.fontSize(12).fillColor("#111827").text(title, 40, y);
};

const ensureSpace = (doc: PDFDocumentType, cursorY: number, heightNeeded: number) => {
  if (cursorY + heightNeeded > doc.page.height - 90) {
    doc.addPage();
    return 50;
  }
  return cursorY;
};

export const buildSingleScanPdf = (scan: ScanReport) => {
  const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
  doc.font(FONT_PATH);

  const score = scan.riskScore ?? scan.confidence;
  const risk = riskLabel(score);
  const badge = badgeColors(risk);

  // Header
  drawShieldIcon(doc, 40, 34);
  doc.fontSize(18).fillColor("#0F172A").text(PROJECT_NAME, 80, 40);
  doc.fontSize(12).fillColor("#1F2937").text(REPORT_TITLE, 80, 64);
  doc.fontSize(10).fillColor("#6B7280").text(ORGANIZATION, 80, 82);
  doc.roundedRect(430, 40, 120, 20, 8).fill("#0F172A");
  doc.fontSize(9).fillColor("#FFFFFF").text(CLASSIFICATION, 442, 46);
  doc.fontSize(9).fillColor("#475569").text("Report Type: Individual Scan", 80, 102);
  doc.fontSize(9).fillColor("#475569").text(`Generated: ${formatEAT(new Date())}`, 320, 102, { align: "right" });
  doc.moveTo(40, 122).lineTo(555, 122).strokeColor("#E2E8F0").stroke();

  let cursorY = 134;

  // Executive Summary
  drawSectionHeader(doc, "Executive Summary", cursorY);
  cursorY += 26;

  const cardWidth = 160;
  const cardHeight = 46;
  const cardGap = 16;
  const row1Y = cursorY;
  const row2Y = row1Y + cardHeight + 12;

  const verdictLabel = scan.result.toUpperCase();
  const verdictStyle = verdictBadge(verdictLabel === "SUSPICIOUS" ? "SUSPICIOUS" : verdictLabel);

  drawCard(doc, 40, row1Y, cardWidth, cardHeight);
  iconTriangle(doc, 50, row1Y + 10, verdictStyle.text);
  doc.fontSize(8).fillColor("#64748B").text("Verdict", 62, row1Y + 8);
  doc.roundedRect(50, row1Y + 22, 90, 18, 6).fill(verdictStyle.fill);
  doc.fillColor(verdictStyle.text).fontSize(9).text(verdictLabel, 58, row1Y + 26);

  drawCard(doc, 40 + cardWidth + cardGap, row1Y, cardWidth, cardHeight);
  iconCircle(doc, 50 + cardWidth + cardGap, row1Y + 12, badge.text);
  doc.fontSize(8).fillColor("#64748B").text("Risk Level", 62 + cardWidth + cardGap, row1Y + 8);
  doc.roundedRect(50 + cardWidth + cardGap, row1Y + 22, 90, 18, 6).fill(badge.fill);
  doc.fillColor(badge.text).fontSize(9).text(risk, 58 + cardWidth + cardGap, row1Y + 26);

  drawCard(doc, 40 + (cardWidth + cardGap) * 2, row1Y, cardWidth, cardHeight);
  iconCircle(doc, 50 + (cardWidth + cardGap) * 2, row1Y + 12, "#0EA5E9");
  doc.fontSize(8).fillColor("#64748B").text("Confidence", 62 + (cardWidth + cardGap) * 2, row1Y + 8);
  doc.fillColor("#0F172A").fontSize(12).text(`${scan.confidence}%`, 50 + (cardWidth + cardGap) * 2, row1Y + 24);

  drawCard(doc, 40, row2Y, cardWidth, cardHeight);
  iconCircle(doc, 50, row2Y + 12, "#22C55E");
  doc.fontSize(8).fillColor("#64748B").text("AI Score", 62, row2Y + 8);
  doc.fillColor("#0F172A").fontSize(12).text(`${score}%`, 50, row2Y + 24);

  drawCard(doc, 40 + cardWidth + cardGap, row2Y, cardWidth, cardHeight);
  iconCircle(doc, 50 + cardWidth + cardGap, row2Y + 12, "#94A3B8");
  doc.fontSize(8).fillColor("#64748B").text("Scan Type", 62 + cardWidth + cardGap, row2Y + 8);
  doc.fillColor("#0F172A").fontSize(12).text(scan.inputType.toUpperCase(), 50 + cardWidth + cardGap, row2Y + 24);

  drawCard(doc, 40 + (cardWidth + cardGap) * 2, row2Y, cardWidth, cardHeight);
  iconCircle(doc, 50 + (cardWidth + cardGap) * 2, row2Y + 12, "#0F172A");
  doc.fontSize(8).fillColor("#64748B").text("Targeted Institution", 62 + (cardWidth + cardGap) * 2, row2Y + 8);
  doc.fillColor("#0F172A").fontSize(9).text(scan.institution || "Unclassified", 50 + (cardWidth + cardGap) * 2, row2Y + 24, { width: cardWidth - 20 });

  cursorY = row2Y + cardHeight + 18;
  drawCard(doc, 40, cursorY, 515, 52);
  doc.fontSize(8).fillColor("#64748B").text("Scan ID", 50, cursorY + 8);
  doc.fillColor("#0F172A").fontSize(9).text(scan.id, 50, cursorY + 22);
  doc.fontSize(8).fillColor("#64748B").text("Detection Timestamp", 320, cursorY + 8);
  doc.fillColor("#0F172A").fontSize(9).text(formatEAT(scan.createdAt), 320, cursorY + 22);

  cursorY += 70;

  // Verdict Highlight
  const verdictBanner = verdictBadge(verdictLabel === "SUSPICIOUS" ? "SUSPICIOUS" : verdictLabel);
  doc.roundedRect(40, cursorY, 515, 46, 8).fill(verdictBanner.fill);
  iconTriangle(doc, 58, cursorY + 14, verdictBanner.text);
  doc.fillColor(verdictBanner.text).fontSize(16).text(`${verdictLabel} — ${risk} RISK`, 82, cursorY + 14);
  cursorY += 66;

  // Scan Details
  cursorY = ensureSpace(doc, cursorY, 120);
  drawSectionHeader(doc, "Scan Details", cursorY);
  cursorY += 26;

  doc.fontSize(9).fillColor("#111827").text(`Type: ${scan.inputType.toUpperCase()}`, 40, cursorY);
  doc.text(`Timestamp: ${formatEAT(scan.createdAt)}`, 280, cursorY);
  cursorY += 16;
  doc.fontSize(9).fillColor("#111827").text(`AI Classification Score: ${score}%`, 40, cursorY);
  cursorY += 16;

  // Content box
  const content = scan.contentPreview || "(content unavailable)";
  const contentHeight = doc.heightOfString(content, { width: 475 });
  cursorY = ensureSpace(doc, cursorY, contentHeight + 34);
  drawCard(doc, 40, cursorY, 515, contentHeight + 22);
  doc.fontSize(8).fillColor("#64748B").text("Analyzed Content", 50, cursorY + 8);
  doc.font("Courier").fillColor("#111827").fontSize(9).text(content, 50, cursorY + 22, { width: 495 });
  doc.font(FONT_PATH);
  cursorY += contentHeight + 40;

  // Indicators
  cursorY = ensureSpace(doc, cursorY, 140);
  drawSectionHeader(doc, "Detection Indicators", cursorY);
  cursorY += 26;
  const primaryNames = new Set([
    "Credential Intent",
    "Bank Impersonation",
    "Suspicious Links",
    "Shortened Links",
    "Urgency Language",
  ]);
  const primary = scan.indicators.filter((i) => primaryNames.has(i.name));
  const secondary = scan.indicators.filter((i) => !primaryNames.has(i.name));

  doc.fontSize(10).fillColor("#0F172A").text("Primary Indicators", 40, cursorY);
  cursorY += 14;
  const primaryList = primary.length ? primary : scan.indicators.filter((i) => i.severity === "high");
  if (!primaryList.length) {
    doc.fillColor("#94A3B8").fontSize(9).text("No primary indicators detected.", 60, cursorY);
    cursorY += 16;
  }
  primaryList.forEach((indicator) => {
    cursorY = ensureSpace(doc, cursorY, 16);
    iconCircle(doc, 48, cursorY + 6, indicator.detected ? "#DC2626" : "#CBD5F5");
    doc.fillColor("#111827").text(indicator.name, 60, cursorY);
    doc.fillColor(indicator.detected ? "#DC2626" : "#94A3B8").text(indicator.detected ? "Detected" : "Not detected", 420, cursorY);
    cursorY += 16;
  });

  cursorY += 6;
  doc.fontSize(10).fillColor("#0F172A").text("Secondary Indicators", 40, cursorY);
  cursorY += 14;
  if (!secondary.length) {
    doc.fillColor("#94A3B8").fontSize(9).text("No secondary indicators detected.", 60, cursorY);
    cursorY += 16;
  }
  secondary.forEach((indicator) => {
    cursorY = ensureSpace(doc, cursorY, 16);
    iconCircle(doc, 48, cursorY + 6, indicator.detected ? "#0EA5E9" : "#CBD5F5");
    doc.fillColor("#111827").text(indicator.name, 60, cursorY);
    doc.fillColor(indicator.detected ? "#0EA5E9" : "#94A3B8").text(indicator.detected ? "Detected" : "Not detected", 420, cursorY);
    cursorY += 16;
  });

  // AI Summary
  cursorY += 6;
  cursorY = ensureSpace(doc, cursorY, 120);
  drawSectionHeader(doc, "AI Analysis Summary", cursorY);
  cursorY += 26;
  drawCard(doc, 40, cursorY, 515, 80);
  doc.fontSize(8).fillColor("#64748B").text("English", 50, cursorY + 8);
  const englishSummary = scan.summary
    ? `Forensic assessment indicates ${scan.summary}`
    : "Forensic assessment unavailable for this scan.";
  doc.fontSize(9).fillColor("#111827").text(englishSummary, 50, cursorY + 22, { width: 495 });
  cursorY += 92;
  cursorY = ensureSpace(doc, cursorY, 80);
  drawCard(doc, 40, cursorY, 515, 80);
  doc.fontSize(8).fillColor("#64748B").text("አማርኛ", 50, cursorY + 8);
  const amSummary = scan.summaryAm || "ለዚህ ፍተሻ የተዘጋጀ የፎሬንሲክ ማብራሪያ አልተገኘም።";
  doc.fontSize(9).fillColor("#111827").text(amSummary, 50, cursorY + 22, { width: 495 });
  cursorY += 96;

  // Recommended Actions
  cursorY = ensureSpace(doc, cursorY, 90);
  drawSectionHeader(doc, "Recommended Actions", cursorY);
  cursorY += 26;
  const actions = verdictLabel === "PHISHING"
    ? [
        "Block the sender and isolate affected endpoints.",
        "Notify the targeted institution via official channels.",
        "Preserve evidence and escalate to incident response.",
      ]
    : verdictLabel === "SUSPICIOUS"
    ? [
        "Validate the message with official channels before responding.",
        "Monitor related accounts for anomalous access.",
        "Educate recipients on safe verification steps.",
      ]
    : [
        "No immediate action required.",
        "Continue monitoring for similar patterns.",
        "Encourage users to verify sensitive requests.",
      ];
  actions.forEach((action) => {
    cursorY = ensureSpace(doc, cursorY, 18);
    iconCircle(doc, 48, cursorY + 6, "#0F172A");
    doc.fontSize(9).fillColor("#111827").text(action, 60, cursorY);
    cursorY += 16;
  });

  addFooter(doc);
  return doc;
};
